/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P4AXlKqyBty
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import { Textarea } from "@/components/ui/textarea"
import Lessons from "@/app/lessons/page";

export function Simulator() {
    return (
        <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
            <div className="relative w-full max-w-md">
                <img
                    alt="Person"
                    className="mx-auto rounded-full shadow-lg"
                    height={200}
                    src="/woman.png"
                    style={{
                        aspectRatio: "400/400",
                        objectFit: "cover",
                    }}
                    width={400}
                />
                <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-full max-w-md p-4 bg-white rounded-lg shadow-lg dark:bg-gray-800">
                    <Textarea
                        className="w-full resize-none focus:outline-none focus:ring-2 focus:ring-gray-500 dark:focus:ring-gray-400"
                        placeholder="Type your message..."
                    />
                </div>
            </div>
        </div>
    )
}

export default Simulator;
