/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LnL5cu3wJBn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Lessons() {
  return (
    <main className="w-full max-w-6xl mx-auto py-12 px-4 md:px-6">
      <div className="space-y-6">
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-sans">Python Fundamentals</h1>
          <p className="mt-4 text-lg text-gray-500 dark:text-gray-400 font-sans">
            Dive into the core concepts of Python programming with our curated lessons.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-800 dark:text-gray-200">
            <div className="p-6 space-y-4">
              <h2 className="text-2xl font-bold font-sans">Data Types</h2>
              <p className="text-gray-500 dark:text-gray-400 font-sans">
                Explore the fundamental data types in Python, including integers, floats, booleans, and strings.
              </p>
              <Link
                className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-gray-900 rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300 font-sans"
                href="#"
              >
                Learn More
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-800 dark:text-gray-200">
            <div className="p-6 space-y-4">
              <h2 className="text-2xl font-bold font-sans">Strings</h2>
              <p className="text-gray-500 dark:text-gray-400 font-sans">
                Dive into the world of strings, including string manipulation, formatting, and common string methods.
              </p>
              <Link
                className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-gray-900 rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300 font-sans"
                href="#"
              >
                Learn More
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-800 dark:text-gray-200">
            <div className="p-6 space-y-4">
              <h2 className="text-2xl font-bold font-sans">Arrays</h2>
              <p className="text-gray-500 dark:text-gray-400 font-sans">
                Discover how to work with arrays, including creating, accessing, and manipulating array elements.
              </p>
              <Link
                className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-gray-900 rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300 font-sans"
                href="#"
              >
                Learn More
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-800 dark:text-gray-200">
            <div className="p-6 space-y-4">
              <h2 className="text-2xl font-bold font-sans">Functions</h2>
              <p className="text-gray-500 dark:text-gray-400 font-sans">
                Explore the power of functions in Python, including defining, calling, and passing arguments to
                functions.
              </p>
              <Link
                className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-gray-900 rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300 font-sans"
                href="#"
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
